# Generated by Django 3.2 on 2021-05-07 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gag.helpers
import gag.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=gag.helpers.UploadTo('category'))),
            ],
            options={
                'verbose_name': 'Katigoriya',
                'verbose_name_plural': 'Katigoriyalar',
            },
            bases=(gag.mixins.TranslateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('file', models.FileField(upload_to=gag.helpers.UploadTo('post'), verbose_name='Rasim/Video')),
                ('like', models.SmallIntegerField(default=0)),
                ('dislike', models.SmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to=gag.helpers.UploadTo('Comment'))),
                ('like', models.SmallIntegerField(default=0)),
                ('dislike', models.SmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
